### ISSUE TITLE
Update Fonts list

### ISSUE THREAD

**Issue by lorro** [seanvm/fontselect-jquery-plugin#10]
Hi,

Google Fonts has more fonts than we're able to choose in the fontselect plugin.
Is it possible to add the missing fonts?
The first ones I came across were Passion One & Montserrat

Thanks

**Comment by seanvm** [comment]
@lorro - Eventually I'd like to get this plugin to the point where it just queries the Google fonts API directly instead of hardcoding the fonts list, as its difficult to stay up to date with a list like that manually.

Unfortunately for now that is quite a ways out from becoming a reality. Currently the fonts themselves are just defined as an array of strings in the `jquery.fontselect.js` file so it is fairly easy to add new ones. At some point I will probably update the list with some of the more popular ones, but feel free to fork this repo and update it, or submit a pull request.
